const LIQUORS = [
  {
    id: "beer-hite",
    name: "Hite",
    type: "맥주",
    region: "대한민국",
    taste: "가볍고 청량함",
    price: "₩2,000",
    calories: "45 kcal / 100ml",
  },
  {
    id: "beer-guinness",
    name: "Guinness Draught",
    type: "맥주",
    region: "아일랜드",
    taste: "묵직하고 로스팅 향",
    price: "₩6,500",
    calories: "54 kcal / 100ml",
  },
  {
    id: "wine-malbec",
    name: "Malbec",
    type: "와인",
    region: "아르헨티나",
    taste: "진한 과일향, 타닌감",
    price: "₩18,000",
    calories: "85 kcal / 100ml",
  },
  {
    id: "wine-chardonnay",
    name: "Chardonnay",
    type: "와인",
    region: "프랑스",
    taste: "산뜻하고 오크향",
    price: "₩22,000",
    calories: "82 kcal / 100ml",
  },
  {
    id: "whiskey-glenfiddich",
    name: "Glenfiddich 12",
    type: "위스키",
    region: "스코틀랜드",
    taste: "부드럽고 배·꿀향",
    price: "₩55,000",
    calories: "231 kcal / 100ml",
  },
  {
    id: "sake-junmai",
    name: "Junmai Sake",
    type: "사케",
    region: "일본",
    taste: "깔끔하고 쌀향",
    price: "₩15,000",
    calories: "103 kcal / 100ml",
  },
  {
    id: "makgeolli-jangsu",
    name: "장수 막걸리",
    type: "막걸리",
    region: "대한민국",
    taste: "새콤달콤, 부드러움",
    price: "₩1,800",
    calories: "46 kcal / 100ml",
  },
  {
    id: "cocktail-mojito",
    name: "Mojito",
    type: "칵테일",
    region: "쿠바",
    taste: "상큼한 라임과 민트",
    price: "₩9,000",
    calories: "60 kcal / 100ml",
  },
  {
    id: "yakju-baekseju",
    name: "백세주",
    type: "약주",
    region: "대한민국",
    taste: "한약재향, 은은한 단맛",
    price: "₩8,500",
    calories: "95 kcal / 100ml",
  },
  {
    id: "fruit-maesilju",
    name: "매실주",
    type: "과일주",
    region: "대한민국",
    taste: "새콤달콤한 매실향",
    price: "₩12,000",
    calories: "90 kcal / 100ml",
  },
];
