use serde::{Deserialize, Serialize};
use std::io::{self, BufRead, Write};
use std::thread;
use std::time::Duration;

#[derive(Debug, Deserialize)]
struct BootstrapConfig {
    seed: u64,
    task_gen_ms: u64,
    zones: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct TaskMessage {
    /// Monotonic task id generated by the child process.
    pub id: u64,
    /// Generated X coordinate.
    pub x: f64,
    /// Generated Y coordinate.
    pub y: f64,
    /// Target zone name for this task.
    pub zone: String,
    /// Human-readable task description.
    pub description: String,
    /// Whether this task is an emergency task.
    pub is_emergency: bool,
    /// Simulated execution time in milliseconds.
    pub execution_ms: u64,
}

fn next_random(seed: &mut u64) -> u64 {
    *seed = seed.wrapping_add(0x9E3779B97F4A7C15);
    let mut z = *seed;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
    z ^ (z >> 31)
}

fn generate_task(task_id: u64, zones: &[String], seed: &mut u64) -> TaskMessage {
    let x = (next_random(seed) % 1000) as f64 / 100.0;
    let y = (next_random(seed) % 1000) as f64 / 100.0;
    let zone_idx = (next_random(seed) as usize) % zones.len();
    let is_emergency = next_random(seed) % 100 < 25;

    let u1 = (next_random(seed) as f64) / u64::MAX as f64;
    let u2 = (next_random(seed) as f64) / u64::MAX as f64;
    let z = (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos();
    let raw = 750.0 + 182.0 * z;
    let execution_ms = raw.clamp(200.0, 1600.0) as u64;

    TaskMessage {
        id: task_id,
        x,
        y,
        zone: zones[zone_idx].clone(),
        description: if is_emergency {
            format!("Emergency response #{task_id}")
        } else {
            format!("Routine delivery #{task_id}")
        },
        is_emergency,
        execution_ms,
    }
}

/// Runs task generation in child-process mode.
///
/// Input contract:
/// - Reads exactly one bootstrap JSON line from stdin.
/// - Expects fields: `seed`, `task_gen_ms`, and `zones`.
///
/// Output contract:
/// - Writes one JSON-encoded `TaskMessage` per line to stdout.
/// - Continues until stdout pipe is closed by parent.
pub fn run_taskgen_child() {
    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();
    let Some(Ok(raw)) = lines.next() else {
        return;
    };

    let Ok(cfg) = serde_json::from_str::<BootstrapConfig>(&raw) else {
        eprintln!("[TaskGenProcess] invalid bootstrap config");
        return;
    };

    if cfg.zones.is_empty() {
        eprintln!("[TaskGenProcess] zones cannot be empty");
        return;
    }

    let mut seed = cfg.seed;
    let mut next_id = 1u64;
    let sleep_ms = cfg.task_gen_ms.max(100);
    let stdout = io::stdout();
    let mut out = stdout.lock();

    loop {
        let task = generate_task(next_id, &cfg.zones, &mut seed);
        next_id = next_id.saturating_add(1);

        if serde_json::to_writer(&mut out, &task).is_err() {
            break;
        }
        if writeln!(out).is_err() {
            break;
        }
        if out.flush().is_err() {
            break;
        }

        thread::sleep(Duration::from_millis(sleep_ms));
    }
}
