pub struct SummaryData {
    /// Number of robots requested by CLI config.
    pub configured_robots: usize,
    /// Actual elapsed wall-clock time in seconds.
    pub elapsed_secs: f64,
    /// Total tasks generated by the producer thread.
    pub generated: u64,
    /// Total tasks completed by all robots.
    pub completed: u64,
    /// Number of completed tasks marked as emergency.
    pub completed_emergency: u64,
    /// Tasks still left in queue at shutdown.
    pub remaining: u64,
    /// Count of direct zone lock acquisition failures.
    pub zone_contention: u64,
    /// Count of scheduler-level deferrals (e.g., no available candidate zones or no suitable task yet).
    pub scheduler_deferrals: u64,
    /// Count of lock-level deferrals where zone acquisition failed and had to retry.
    pub zone_lock_deferrals: u64,
    /// Number of successful task fetches used as denominator for scheduler wait average.
    pub scheduler_pick_count: u64,
    /// Sum of scheduler waiting time in nanoseconds before a task is fetched.
    pub scheduler_wait_total_ns: u64,
    /// Maximum scheduler waiting time in nanoseconds before a task is fetched.
    pub scheduler_wait_max_ns: u64,
    /// Number of successful zone lock acquisitions.
    pub zone_acquire_success: u64,
    /// Sum of all zone lock acquisition latencies in nanoseconds.
    pub zone_latency_total_ns: u64,
    /// Maximum single zone lock acquisition latency in nanoseconds.
    pub zone_latency_max_ns: u64,
    /// Sum of end-to-end wait from deferral period to lock acquisition success, in nanoseconds.
    pub zone_wait_total_ns: u64,
    /// Maximum end-to-end wait from deferral period to lock acquisition success, in nanoseconds.
    pub zone_wait_max_ns: u64,
    /// Sum of end-to-end waits for tasks that had at least one deferral, in nanoseconds.
    pub zone_wait_deferred_only_total_ns: u64,
    /// Count of completed tasks that had at least one deferral before lock success.
    pub zone_wait_deferred_only_count: u64,
    /// Highest observed queue length during the run.
    pub peak_queue: u64,
    /// Deterministic fingerprint of generated workload sequence.
    pub workload_fingerprint: u64,
    /// Total heartbeat messages sent by robot threads.
    pub total_heartbeats_sent: u64,
    /// Number of offline timeout detections by health monitor.
    pub timeout_detections: u64,
    /// Robot IDs currently considered online at shutdown.
    pub online_robots: Vec<u64>,
    /// Robot IDs currently considered offline at shutdown.
    pub offline_robots: Vec<u64>,
    /// Completed task count per robot index (robot_id - 1).
    pub per_robot_completed: Vec<u64>,
}

pub fn print_summary(data: &SummaryData) {
    let backlog = data.generated.saturating_sub(data.completed);
    let in_flight_estimate = backlog.saturating_sub(data.remaining);
    let completion_rate = if data.generated > 0 {
        data.completed as f64 * 100.0 / data.generated as f64
    } else {
        0.0
    };
    let throughput = if data.elapsed_secs > 0.0 {
        data.completed as f64 / data.elapsed_secs
    } else {
        0.0
    };
    let zone_latency_avg_ms = if data.zone_acquire_success > 0 {
        (data.zone_latency_total_ns as f64 / data.zone_acquire_success as f64) / 1_000_000.0
    } else {
        0.0
    };
    let zone_latency_max_ms = data.zone_latency_max_ns as f64 / 1_000_000.0;
    let zone_wait_avg_ms = if data.zone_acquire_success > 0 {
        (data.zone_wait_total_ns as f64 / data.zone_acquire_success as f64) / 1_000_000.0
    } else {
        0.0
    };
    let zone_wait_max_ms = data.zone_wait_max_ns as f64 / 1_000_000.0;
    let zone_wait_deferred_only_avg_ms = if data.zone_wait_deferred_only_count > 0 {
        (data.zone_wait_deferred_only_total_ns as f64 / data.zone_wait_deferred_only_count as f64)
            / 1_000_000.0
    } else {
        0.0
    };
    let scheduler_wait_avg_ms = if data.scheduler_pick_count > 0 {
        (data.scheduler_wait_total_ns as f64 / data.scheduler_pick_count as f64) / 1_000_000.0
    } else {
        0.0
    };
    let scheduler_wait_max_ms = data.scheduler_wait_max_ns as f64 / 1_000_000.0;

    println!("\n========== Simulation Summary ==========");
    println!("Configured robots         : {}", data.configured_robots);
    println!("Actual runtime (seconds)  : {:.2}", data.elapsed_secs);
    println!("Generated tasks           : {}", data.generated);
    println!("Completed tasks           : {}", data.completed);
    println!("Completed emergency tasks : {}", data.completed_emergency);
    println!("Remaining queue tasks     : {}", data.remaining);
    println!("Estimated in-flight tasks : {}", in_flight_estimate);
    println!("Completion rate           : {:.2}%", completion_rate);
    println!("Throughput                : {:.2} tasks/sec", throughput);
    println!("Zone lock latency (avg)   : {:.3} ms", zone_latency_avg_ms);
    println!("Zone lock latency (max)   : {:.3} ms", zone_latency_max_ms);
    println!("Zone wait incl defer (avg): {:.3} ms", zone_wait_avg_ms);
    println!("Zone wait incl defer (max): {:.3} ms", zone_wait_max_ms);
    println!(
        "Deferred tasks wait (avg) : {:.3} ms",
        zone_wait_deferred_only_avg_ms
    );
    println!("Zone contention count     : {}", data.zone_contention);
    println!("Scheduler deferrals       : {}", data.scheduler_deferrals);
    println!("Scheduler wait (avg)      : {:.3} ms", scheduler_wait_avg_ms);
    println!("Scheduler wait (max)      : {:.3} ms", scheduler_wait_max_ms);
    println!("Zone lock deferrals       : {}", data.zone_lock_deferrals);
    println!("Peak queue length         : {}", data.peak_queue);
    println!(
        "Workload fingerprint      : 0x{:016X}",
        data.workload_fingerprint
    );
    println!("Total heartbeats sent     : {}", data.total_heartbeats_sent);
    println!("Timeout detections        : {}", data.timeout_detections);
    println!("Online robots             : {:?}", data.online_robots);
    println!("Offline robots            : {:?}", data.offline_robots);
    println!("Per-robot completion:");
    for robot_id in 1..=data.configured_robots {
        let count = data
            .per_robot_completed
            .get(robot_id.saturating_sub(1))
            .copied()
            .unwrap_or(0);
        println!("  Robot {:>2}: {} tasks", robot_id, count);
    }
    println!("========================================");
}
